version: "3"

services:
  web:
    build: .
    # build:
    #   context: .
    #   dockerfile: Dockerfile.dev # debug
    image: misskey-v11-app
    container_name: misskey_v11_app
    restart: always
    links:
      - db
      - redis
#      - es
    networks:
      - internal_network
      - shared
    volumes:
      - ./files:/misskey/files
      - ./.config:/misskey/.config

  redis:
    restart: always
    container_name: misskey_v11_redis
    image: redis:7.0-alpine
    networks:
      - internal_network
    volumes:
      - ./redis:/data

  db:
    restart: always
    container_name: misskey_v11_db
    image: postgres:15.4-alpine3.18
    networks:
      - internal_network
    env_file:
      - .config/docker.env
    volumes:
      - ./db:/var/lib/postgresql/data

#  es:
#    restart: always
#    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.4.2
#    environment:
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    networks:
#      - internal_network
#    volumes:
#      - ./elasticsearch:/usr/share/elasticsearch/data

networks:
  internal_network:
    internal: true
  shared:
    external: true
