FROM node:20.11.0-alpine3.19

ENV NODE_ENV=production

WORKDIR /misskey

RUN apk add --no-cache \
    autoconf automake file git g++ gcc libc-dev libtool make \
    nasm pkgconfig python3 tzdata zlib-dev \
    && cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime \
    && corepack enable pnpm

# Install runtime dependencies
RUN apk add --no-cache tini

COPY package.json pnpm-lock.yaml ./
RUN pnpm i --dev --frozen-lockfile && npx update-browserslist-db@latest

COPY .eslintrc.json .mocharc.json .npmrc .swcrc gulpfile.js index.js ormconfig.js tsconfig.json webpack.config.js ./
COPY assets/ ./assets/
COPY locales/ ./locales/
COPY migration/ ./migration/
COPY LICENSE docker-entrypoint.sh gulpfile.js index.js ormconfig.js renovate.json ./
COPY src/ ./src/
RUN pnpm build

ENTRYPOINT ["/sbin/tini", "--"]
CMD ["./docker-entrypoint.sh"]
